version: "3.8"

services:
  postgres_db:
    image: postgres
    container_name: postgresql_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chattingbox
    ports:
      - '5432:5432'

  recipe:
    container_name: chattingbox_con
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: giaphuc/chattingbox:1.0.0
    ports:
      - '8080:8080' #<computer/host_port>:<container_port>
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/chattingbox
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres_db
